language: c
os:
  - linux
arch:
  - amd64
  # - ppc64le  # Apply patch
  - arm64-graviton2
virt: lxd
group: edge

install: ci-base/install.sh travis sysbench
script: ./run.sh
jobs:
  exclude:
  - os: osx
    arch: ppc64le
  - os: osx
    arch: arm64
