version: 2.1

executors:
  machine_medium:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    environment:
      FLAVOR_NAME: machine_medium
      IMAGE_NAME: ubuntu
  # machine_large:
  #   machine:
  #     image: ubuntu-1604:201903-01
  #   resource_class: large
  #   environment:
  #     FLAVOR_NAME: machine_large
  #     IMAGE_NAME: ubuntu

jobs:
  run_machine_medium:
    executor: machine_medium
    steps:
      - checkout
      - run:
          name: Run tests
          command: .circleci/run.sh

  # run_machine_large:
  #   executor: machine_large
  #   steps:
  #     - checkout
  #     - run:
  #         name: Run tests
  #         command: .circleci/run.sh

workflows:
  version: 2
  my-workflow:
    jobs:
      - run_machine_medium:
          context: cloudbeast
      # - run_machine_large:
      # context: cloudbeast
